I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 32, in script
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/lim/Documents/sketchboard/renpy-6.15.7-sdk/renpy/execution.py", line 288, in run
    node.execute()
  File "/home/lim/Documents/sketchboard/renpy-6.15.7-sdk/renpy/ast.py", line 1110, in execute
    renpy.exports.with_statement(trans, paired)
  File "/home/lim/Documents/sketchboard/renpy-6.15.7-sdk/renpy/exports.py", line 946, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/lim/Documents/sketchboard/renpy-6.15.7-sdk/renpy/display/core.py", line 1531, in do_with
    clear=clear)
  File "/home/lim/Documents/sketchboard/renpy-6.15.7-sdk/renpy/display/core.py", line 1853, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/home/lim/Documents/sketchboard/renpy-6.15.7-sdk/renpy/display/core.py", line 2056, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Linux-3.7.10-1.16-desktop-x86_64-with-SuSE-12.3-x86_64
Ren'Py 6.15.7.374
A Ren'Py Game 0.0
